export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SELECTED_STORY = 'SELECTED_STORY';